class MotivationUtils {
  static const List<String> _quotes = [
    "The only bad workout is the one that didn't happen.",
    "Stop waiting for motivation. It doesn't exist. Get up and go.",
    "You don't get the body you want by wishing for it.",
    "Pain is temporary. Skipping leg day is forever.",
    "Every rep you don't do is a rep your competition did.",
    "Your future self is watching. Don't embarrass them.",
    "The iron never lies. It shows exactly what you put in.",
    "Comfort kills progress. Get uncomfortable.",
    "Someone somewhere is training to beat you. Are you training?",
    "Rest days are earned. Lazy days are wasted.",
    "You came this far. Don't quit now.",
    "Sweat is just fat crying. Make it cry harder.",
    "The gym doesn't care about your excuses.",
    "Small progress is still progress. But stop making it small.",
    "Your body achieves what your mind believes.",
    "Weak people make excuses. Strong people make progress.",
    "No one remembers who came second. Train like you mean it.",
    "Champions aren't born in comfort zones.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Get up. Show up. Shut up. Lift.",
    "You're not tired. You're just lazy. There's a difference.",
    "The weight won't lift itself. Unfortunately.",
    "One more rep. Always one more rep.",
    "Your excuses are boring. Your results won't be.",
    "Discipline beats motivation every single day.",
    "Iron sharpens iron. Get in the damn gym.",
    "Another day another chance to not be a coward.",
    "You vs you. Stop blaming the world.",
    "Progress is made outside the comfort zone.",
    "Eat, sleep, lift, repeat. That's it.",
    "The mirror is honest. Are you listening?",
    "Weak is not an option when you have a goal.",
    "The barbell doesn't know your problems. Lift it anyway.",
    "Mediocrity is comfortable. Excellence is not. Choose wisely.",
    "You don't have to like it. You just have to do it.",
    "Think less. Lift more.",
    "Your body is capable of more than you know.",
    "Soreness is weakness leaving the body.",
    "Stop talking about your dream body and start building it.",
    "Every champion was once a beginner who refused to quit.",
    "Hard work beats talent when talent gets lazy.",
    "Excuses are for people who don't really want it.",
    "Treat every workout like it's your last chance.",
    "The gym is cheaper than therapy and has better results.",
    "Don't count the days. Make the days count.",
    "Success is not given. It's taken.",
    "You can sleep when you hit your goal weight.",
    "Nobody said this would be easy. Get over it.",
    "Train insane or remain the same.",
    "Progress not perfection. But stop making excuses.",
    "The weights don't care about your feelings.",
    "Be obsessed or be average.",
    "Your health is an investment not an expense.",
    "No shortcuts. No excuses. Just results.",
    "Work harder than you did yesterday.",
    "Stop being your own worst enemy.",
    "Failure is not falling down. It's refusing to get up.",
    "Winners never quit and quitters never win.",
    "You're only one workout away from a good mood.",
    "Push harder than yesterday if you want a different tomorrow.",
    "Strive for progress not perfection.",
    "Hustle for that muscle.",
    "Train like a beast. Look like a beauty.",
    "Sore today. Strong tomorrow.",
    "Don't wish for it. Work for it.",
    "Strength doesn't come from what you can do. It comes from overcoming what you thought you couldn't.",
    "The last three or four reps is what makes the muscle grow.",
    "You have to push through the bad days to earn the good ones.",
    "Results don't lie. Excuses do.",
    "Be stronger than your excuses.",
    "Show up even when you don't feel like it.",
    "The body achieves what the mind allows.",
    "One day at a time. One rep at a time.",
    "Go hard or go home. No in between.",
    "It's not about having time. It's about making time.",
    "Nothing worth having comes easy.",
    "The clock is ticking. Are you moving?",
    "Sweat now. Flex later.",
    "What you do today determines who you are tomorrow.",
    "A year from now you'll wish you started today.",
    "If it doesn't challenge you it doesn't change you.",
    "Do it for the person you want to become.",
    "Success is the sum of small efforts repeated day in and day out.",
    "Every setback is a setup for a comeback.",
    "Build yourself so nobody can break you.",
    "The limit is in your head not your muscles.",
    "Either you run the day or the day runs you.",
    "Wake up. Work out. Beat yesterday.",
    "Good things come to those who sweat.",
    "Your body is not a problem to be fixed. It's a machine to be fueled.",
    "The gym is your church. Show some reverence.",
    "No guts. No glory.",
    "Sleep like a champion. Eat like a champion. Train like a champion.",
    "Don't confuse activity with achievement. The reps have to count.",
    "Decide. Commit. Succeed.",
    "The loudest voice in the room is the one inside your head. Tell it to shut up and lift.",
    "You didn't come this far to only come this far.",
    "Be the hardest worker in the room.",
    "What gets measured gets managed. Track your gains.",
    "Don't stop when you're tired. Stop when you're done.",
    "Pain is the feeling of weakness leaving your body.",
    "Tough times don't last. Tough people do.",
    "The body you want is on the other side of the excuse you're making.",
    "You can make excuses or you can make progress. Not both.",
    "Consistency is what transforms average into excellence.",
    "Every workout is progress even when it doesn't feel like it.",
    "Don't let the scale define you. Let your effort define you.",
    "Your only competition is who you were yesterday.",
    "If you think lifting weights is dangerous try being weak.",
    "Laziness is the enemy of everything you want.",
    "Earn your rest days. Otherwise they're just lazy days.",
    "The grind doesn't stop. Neither should you.",
    "Stronger every day. That's the plan.",
    "Make your workout count not just your calories.",
    "Mind over matter. Now stop whining and lift.",
    "The iron never lies. Are you lying to yourself?",
    "Build the habit. The habit will build you.",
    "Stop waiting to feel ready. You'll never feel ready.",
    "Champions show up when they don't feel like it.",
    "Winners find a way. Losers find an excuse.",
    "If your body says stop your mind says go.",
    "One more set never killed anyone. Quit whining.",
    "Pain is temporary. Pride is forever.",
    "The strongest people are not those who show strength but those who fight hardest when things seem dark.",
    "Today's pain is tomorrow's power.",
    "You earn your body. Nobody gives it to you.",
    "Be relentless.",
    "You've come too far to take it easy now.",
    "Hustle in silence. Let your results shout.",
    "Stay focused. Stay dedicated. Stay alive in the gym.",
    "Every workout is a brick in the building of your best self.",
    "Stop scaling back your goals to match your comfort level.",
    "Nobody who ever gave their best regretted it.",
    "You don't need motivation. You need discipline.",
    "The only easy day was yesterday.",
    "Suffer now and live the rest of your life as a champion.",
    "Great things never come from comfort zones.",
    "Training is not punishment. It's a privilege.",
    "You control your destiny with every choice you make.",
    "The secret to getting ahead is getting started.",
    "Not every day will be a PR. But every day is a chance to show up.",
    "You are stronger than your excuses.",
    "Be so good they can't ignore you.",
    "Forget the mistakes. Remember the lessons.",
    "The iron doesn't forgive laziness. Neither should you.",
    "Real athletes train in silence and let their bodies do the talking.",
    "Don't be motivated. Be disciplined.",
    "Your willpower is a muscle. Train it.",
    "Excellence is a habit. Cultivate it daily.",
    "When you feel like quitting remember why you started.",
    "Results happen over time not overnight.",
    "You will not always be motivated. That's why we build habits.",
    "Do what you have to do to get where you want to be.",
    "Dedication means doing it even when it's boring.",
    "The cost of regret is greater than the cost of discipline.",
    "One hour of pain is better than a lifetime of regret.",
    "Sacrifice today for a better tomorrow.",
    "Your body is a temple. Stop treating it like a dumpster.",
    "Earn your food. Earn your rest. Earn everything.",
    "You are what you repeatedly do. Choose greatness.",
    "Stop overthinking and start over-doing.",
    "Failure to prepare is preparing to fail.",
    "Don't compare your chapter one to someone else's chapter thirty.",
    "Keep going. Your future self will thank you.",
    "The way you do anything is the way you do everything.",
    "Work hard enough that you can't make excuses.",
    "Hard work is painful when life is devoid of purpose.",
    "The price of success is paid upfront in the currency of sweat.",
    "You want change? Then change.",
    "Nothing changes if nothing changes.",
    "You are one decision away from a completely different life.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Lose your excuses and find your results.",
    "Obsessed is a word the lazy use to describe the dedicated.",
    "Train ugly. Eat clean. Sleep hard.",
    "Show up when you don't feel like it. That's real commitment.",
    "Find your limit. Then destroy it.",
    "Don't stop until you're proud.",
    "Risk it for the biscuit. No wait — skip the biscuit and risk it anyway.",
    "Abs are made in the kitchen and revealed in the gym.",
    "You don't have to be extreme. Just consistent.",
    "Repetition is the mother of skill.",
    "Excellence is not a destination. It's a continuous journey.",
    "Progress over perfection. But make it consistent.",
    "Don't major in minor things.",
    "Do it scared. Do it tired. But do it.",
    "Discipline is choosing between what you want now and what you want most.",
    "Your habits will make you or break you.",
    "Outwork your yesterday.",
    "The road to success is always under construction.",
    "Legendary is not born. It's built — one rep at a time.",
    "Show the gym who's boss today.",
    "You don't grow by staying comfortable.",
    "If you're not growing you're dying.",
    "Every squat you skip is one your future self regrets.",
    "Real gains come from real work. Period.",
    "Stop playing small.",
    "The best project you'll ever work on is yourself.",
    "Dedication separates the doers from the dreamers.",
    "You don't need a gym full of equipment. You need full commitment.",
    "Hard days are your best days in disguise.",
    "The war is won or lost before you walk into the gym.",
    "Mentality is everything in fitness.",
    "Show up. Push harder. Go home. Repeat.",
    "The longer you wait to start the longer it takes to finish.",
    "You are your greatest investment.",
    "Time under tension builds muscle. Time spent excusing builds nothing.",
    "Lift heavy. Eat right. Sleep well. Repeat forever.",
    "No one cares how you feel. They care what you do about it.",
    "Your comfort zone will kill your potential.",
    "Be more interested in your character than your reputation.",
    "Perfectionists never start. Start ugly.",
    "Showing up is half the battle. The other half is not quitting halfway.",
    "Grit looks boring to outsiders and feels everything to insiders.",
    "One pound at a time. One rep at a time. One day at a time.",
    "Work in silence. Results speak loudly.",
    "Die with memories not dreams.",
    "Force yourself to do the thing you're afraid of.",
    "You're not tired. You haven't even started yet.",
    "Stop measuring. Start doing.",
    "Champions are made when nobody is watching.",
    "The gym is the one place where you get exactly what you earn.",
    "Leave your ego at the door. Pick up the iron.",
    "Nothing comes to the sleeping man but dreams.",
    "Build your body. Sharpen your mind. Silence your doubts.",
    "Stay the course even when the course is steep.",
    "Progress is the goal. Failure is the teacher.",
    "Talk less. Lift more.",
    "Your next goal should scare you a little.",
    "Relentless forward motion. That's the motto.",
    "Fall in love with the process.",
    "Train like you'll live forever. Live like you'll die tomorrow.",
    "Real power is control. Control over self.",
    "Let your gains do the talking.",
    "One workout won't get you there but missing one will delay you.",
    "Big goals require big action.",
    "Don't dial it back. Turn it up.",
    "Success isn't for everyone. That's why it's called success.",
    "Be the 1% that goes hard when everyone else goes home.",
    "Grind now. Shine later.",
    "Get comfortable being uncomfortable.",
    "Today's effort is tomorrow's result.",
    "Steel sharpens steel. Get around people who push you.",
    "The only way out is through.",
    "Embrace the struggle. It means you're growing.",
    "The body you want won't build itself. Neither will your excuses.",
    "What's heavy for you is a warm-up for someone else. Go harder.",
    "Chase goals not compliments.",
    "The comeback is always stronger than the setback.",
    "Failure is feedback. Take the note and get back up.",
    "Brick by brick you build a fortress.",
    "Dream big. Train bigger.",
    "Fall forward. At least you're moving.",
    "You don't need perfect. You need real effort.",
    "Start where you are. Use what you have. Do what you can.",
    "Every rep brings you closer. Every skip takes you further.",
    "The days you want to give up are training days too.",
    "Make yourself proud. Not Instagram likes.",
    "No filter needed when you've actually put in the work.",
    "Be patient. Be consistent. Be relentless.",
    "Be the version of yourself that didn't have an excuse.",
    "One day or day one. You decide.",
    "Never skip twice. The second skip is a habit.",
    "Calories didn't count themselves to get here. Don't let them.",
    "You are what you eat and how you train. Choose carefully.",
    "Hunger is not weakness. It means you're working.",
    "Close the app for motivation and open the gym door instead.",
    "Every time you skip a workout you're choosing to stay the same.",
    "Stay humble. Stay hungry. Stay lifting.",
    "The best revenge is a fit body.",
    "Make your muscles match your ambitions.",
    "No one is coming to save you. Lift yourself.",
    "You weren't born to be average.",
    "Doubt kills more dreams than failure ever will.",
    "The scoreboard doesn't lie. Neither does your progress log.",
    "Train your mind first. The body follows.",
    "Some people dream of success. Others wake up and work for it.",
    "Sweat equity is the greatest investment you can make.",
    "The hardest lift is getting off the couch.",
    "Build habits that your future self will thank you for.",
    "Your weaknesses are just strengths you haven't unlocked yet.",
    "No retreat. No surrender. Full send.",
    "Pursue your goals with the intensity of a man with nothing to lose.",
    "The truth is that champions are forged in the fire of self-discipline.",
    "Every rep is a vote for the person you're becoming.",
    "Effort is never wasted even if it doesn't go the way you planned.",
    "You can't out-train a bad mindset.",
    "Own the day or the day owns you.",
    "You're not too old. You're not too busy. You're just not ready yet.",
    "Progress starts the second you decide to stop making excuses.",
  ];

  static String getTodayQuote() {
    final dayOfYear = DateTime.now().difference(DateTime(DateTime.now().year)).inDays;
    return _quotes[dayOfYear % _quotes.length];
  }

  static String getRandomQuote() {
    final index = DateTime.now().millisecondsSinceEpoch % _quotes.length;
    return _quotes[index];
  }

  static List<String> get allQuotes => List.unmodifiable(_quotes);

  static int get totalCount => _quotes.length;
}
