class SplashQuotes {
  static const List<String> quotes = [
    "Hey welcome, I hope you are not tired for this gym session. Let's go!",
    "Look who showed up, let's pretend you're going to lift heavy today. Get to work.",
    "Finally out of bed? Try not to embarrass yourself. No excuses.",
    "Welcome back, let's see if you can survive today's workout. Move it.",
    "Ready to suffer? I'm sure you'll do your 'best'. Start sweating.",
    "Back for more pain? It's time to actually sweat. Prove me wrong.",
    "Let's get this over with, let's burn off whatever you ate yesterday. Don't disappoint me.",
    "Don't tell me you're tired, try to lift more than the empty bar this time. Make it count.",
    "Oh great, you're here. Don't make me laugh with your weights. Do it now.",
    "Time to lift, let's see if those muscles are just for show. Get moving.",
    "Stop crying and time to pretend you know what you are doing. Show me something.",
    "I hope you brought your muscles. I hope you didn't skip leg day again. Stop complaining.",
    "Guess who needs a workout. Let's hope you last longer than 20 minutes. Get under the bar.",
    "Still trying? Maybe today you'll actually break a sweat. Push harder.",
    "You call that a warm up? Stop looking at your phone and lift. Earn your rest.",
    "Here comes the champ... not. I know you're tired, but nobody cares. Don't stop early.",
    "Ah, the legend returns. Let's fix that posture today. Finish strong.",
    "Don't skip today, see if you can lift your own body weight. Let's go!",
    "Look who's back, I doubt you're ready for this. Get to work.",
    "Ready for the pain? I hope you are not tired for this gym session. No excuses.",
    "Hey welcome, try not to embarrass yourself. Move it.",
    "Oh, it's you again. Let's see if you can survive today's workout. Start sweating.",
    "Look who showed up, it's time to actually sweat. Prove me wrong.",
    "Finally out of bed? Let's burn off whatever you ate yesterday. Don't disappoint me.",
    "Welcome back, try to lift more than the empty bar this time. Make it count.",
    "Ready to suffer? Don't make me laugh with your weights. Do it now.",
    "Back for more pain? Let's see if those muscles are just for show. Get moving.",
    "Let's get this over with, time to pretend you know what you are doing. Show me something.",
    "Don't tell me you're tired, I hope you didn't skip leg day again. Stop complaining.",
    "Oh great, you're here. Let's hope you last longer than 20 minutes. Get under the bar.",
    "Time to lift, maybe today you'll actually break a sweat. Push harder.",
    "Stop crying and stop looking at your phone and lift. Earn your rest.",
    "I hope you brought your muscles. I know you're tired, but nobody cares. Don't stop early.",
    "Guess who needs a workout. Let's fix that posture today. Finish strong.",
    "Still trying? See if you can lift your own body weight. Let's go!",
    "You call that a warm up? I doubt you're ready for this. Get to work.",
    "Oh, it's you again, let's pretend you're going to lift heavy today. No excuses.",
    "Finally out of bed? I'm sure you'll do your 'best'. Move it.",
    "Ready to suffer? I hope you are not tired for this gym session. Prove me wrong.",
    "Let's get this over with, let's see if you can survive today's workout. Don't disappoint me.",
    "Don't tell me you're tired, try not to embarrass yourself. Make it count.",
    "Time to lift, let's burn off whatever you ate yesterday. Do it now.",
    "I hope you brought your muscles. Try to lift more than the empty bar this time. Get moving.",
    "Still trying? Don't make me laugh with your weights. Show me something.",
    "Here comes the champ... not. Let's see if those muscles are just for show. Stop complaining.",
    "Don't skip today, time to pretend you know what you are doing. Get under the bar.",
    "Ready for the pain? I hope you didn't skip leg day again. Push harder.",
    "Look who showed up, let's hope you last longer than 20 minutes. Earn your rest.",
    "Welcome back, maybe today you'll actually break a sweat. Don't stop early.",
    "Back for more pain? Stop looking at your phone and lift. Finish strong."
  ];
}
