class SplashQuotes {
  static const List<String> quotes = [
    "Hey welcome, I hope you are not tired for this gym session. Let's go!",
    "Look who showed up, let's pretend you're going to lift heavy today. Get to work.",
    "Finally out of bed? Try not to embarrass yourself. No excuses.",
    "Welcome back, let's see if you can survive today's workout. Move it.",
    "Ready to suffer? I'm sure you'll do your 'best'. Start sweating.",
    "Back for more pain? It's time to actually sweat. Prove me wrong.",
    "Let's get this over with, let's burn off whatever you ate yesterday. Don't disappoint me.",
    "Don't tell me you're tired, try to lift more than the empty bar this time. Make it count.",
    "Oh great, you're here. Don't make me laugh with your weights. Do it now.",
    "Time to lift, let's see if those muscles are just for show. Get moving.",
    "Stop crying and time to pretend you know what you are doing. Show me something.",
    "I hope you brought your muscles. I hope you didn't skip leg day again. Stop complaining.",
    "Guess who needs a workout. Let's hope you last longer than 20 minutes. Get under the bar.",
    "Still trying? Maybe today you'll actually break a sweat. Push harder.",
    "You call that a warm up? Stop looking at your phone and lift. Earn your rest.",
    "Here comes the champ... not. I know you're tired, but nobody cares. Don't stop early.",
    "Ah, the legend returns. Let's fix that posture today. Finish strong.",
    "Don't skip today, see if you can lift your own body weight. Let's go!",
    "Look who's back, I doubt you're ready for this. Get to work.",
    "Ready for the pain? I hope you are not tired for this gym session. No excuses.",
    "Hey welcome, try not to embarrass yourself. Move it.",
    "Oh, it's you again. Let's see if you can survive today's workout. Start sweating.",
    "Look who showed up, it's time to actually sweat. Prove me wrong.",
    "Finally out of bed? Let's burn off whatever you ate yesterday. Don't disappoint me.",
    "Welcome back, try to lift more than the empty bar this time. Make it count.",
    "Ready to suffer? Don't make me laugh with your weights. Do it now.",
    "Back for more pain? Let's see if those muscles are just for show. Get moving.",
    "Let's get this over with, time to pretend you know what you are doing. Show me something.",
    "Don't tell me you're tired, I hope you didn't skip leg day again. Stop complaining.",
    "Oh great, you're here. Let's hope you last longer than 20 minutes. Get under the bar.",
    "Time to lift, maybe today you'll actually break a sweat. Push harder.",
    "Stop crying and stop looking at your phone and lift. Earn your rest.",
    "I hope you brought your muscles. I know you're tired, but nobody cares. Don't stop early.",
    "Guess who needs a workout. Let's fix that posture today. Finish strong.",
    "Still trying? See if you can lift your own body weight. Let's go!",
    "You call that a warm up? I doubt you're ready for this. Get to work.",
    "Oh, it's you again, let's pretend you're going to lift heavy today. No excuses.",
    "Finally out of bed? I'm sure you'll do your 'best'. Move it.",
    "Ready to suffer? I hope you are not tired for this gym session. Prove me wrong.",
    "Let's get this over with, let's see if you can survive today's workout. Don't disappoint me.",
    "Don't tell me you're tired, try not to embarrass yourself. Make it count.",
    "Time to lift, let's burn off whatever you ate yesterday. Do it now.",
    "I hope you brought your muscles. Try to lift more than the empty bar this time. Get moving.",
    "Still trying? Don't make me laugh with your weights. Show me something.",
    "Here comes the champ... not. Let's see if those muscles are just for show. Stop complaining.",
    "Don't skip today, time to pretend you know what you are doing. Get under the bar.",
    "Ready for the pain? I hope you didn't skip leg day again. Push harder.",
    "Look who showed up, let's hope you last longer than 20 minutes. Earn your rest.",
    "Welcome back, maybe today you'll actually break a sweat. Don't stop early.",
    "Back for more pain? Stop looking at your phone and lift. Finish strong.",
    "Well look at that, you actually showed up. Try not to waste everyone's time today.",
    "So you decided to train today? Good. Now prove you're not just here for the selfies.",
    "If you're going to stand around, at least pretend you're thinking about lifting.",
    "You came this far, might as well lift something heavier than your phone.",
    "If excuses burned calories you'd already be shredded. Start lifting.",
    "Don't worry, the weights won't bite. But they might expose you.",
    "That warm-up looked suspiciously like your max effort. Try again.",
    "You're here now, so stop negotiating with gravity and pick something up.",
    "Congratulations on arriving. Now let's see if you actually train.",
    "Don't worry if it's hard. Being weak forever is harder.",
    "You walked into the gym. That's the easy part. The hard part is not quitting.",
    "If you're waiting for motivation you're going to be waiting all day.",
    "The bar isn't going to lift itself. And neither are your standards.",
    "You said you wanted progress. This is the part where you earn it.",
    "Resting already? The workout barely knows you exist yet.",
    "If effort were optional you'd probably skip that too.",
    "You came to train, not to decorate the bench. Move.",
    "Today's workout is simple: stop being comfortable.",
    "If that set felt easy, congratulations. That means you didn't try.",
    "The mirror won't build muscle. The barbell might.",
    "You don't need luck. You need another set.",
    "If you quit now the couch will be proud of you.",
    "Training is optional. Regret is permanent.",
    "You're not tired, you're negotiating with effort.",
    "Pick the weight up. Your future self is watching.",
    "If the set scares you, it's probably the one you need.",
    "You didn't come here to stay average. So stop acting like it.",
    "Muscles grow after the moment you want to quit.",
    "If you're waiting for the perfect time, it's already late.",
    "That weight isn't heavy. Your excuses are.",
    "Every skipped rep is a vote for staying the same.",
    "You can complain after the last rep. Until then, lift.",
    "If you stop now, the dumbbells win.",
    "The workout doesn't care how you feel. Finish it.",
    "If you're still talking, you're not lifting.",
    "You're stronger than yesterday. Now prove it.",
    "The only bad workout is the one you quit early.",
    "Either the weight moves, or your pride does.",
    "You don't need talent for this. Just stubbornness.",
    "If today hurts, good. That's progress knocking.",
    "The barbell is honest. It exposes effort.",
    "If you want results, stop negotiating with effort.",
    "Every rep is a tiny rebellion against laziness.",
    "One more set. Then another. That's how this works.",
    "The clock is running. Make the workout count.",
    "If it burns, you're doing it right.",
    "The gym doesn't reward comfort. It rewards effort.",
    "If you're breathing, you can do another rep."
  ];
}
